[package]
name = "pb"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.10"
log = "0.4"
clap = {version = "4", features = ["derive"]}
actix-web = "4"
actix-files = "0.6"
rusqlite = "0.28"
serde = {version = "1", features = ["derive"]}
regex = "1"
